// 더미 데이터 생성
const dummyPosts = [
  { id: 1, title: "첫 번째 책갈피", content: "이 책은 매우 재미있어요!", author: "저자1", imageUrl: "https://example.com/book1.jpg" },
  { id: 2, title: "두 번째 책갈피", content: "이 책은 정말 유익해요!", author: "저자2", imageUrl: "https://example.com/book2.jpg" },
  { id: 3, title: "세 번째 책갈피", content: "이 책은 최고입니다!", author: "저자3", imageUrl: "https://example.com/book3.jpg" },
  { id: 4, title: "네 번째 책갈피", content: "이 책은 재미없어요!", author: "저자4", imageUrl: "https://example.com/book4.jpg" },
  { id: 5, title: "다섯 번째 책갈피", content: "이 책은 지루하지만 교훈적입니다.", author: "저자5", imageUrl: "https://example.com/book5.jpg" },
  { id: 6, title: "여섯 번째 책갈피", content: "이 책은 굉장히 감동적이에요.", author: "저자6", imageUrl: "https://example.com/book6.jpg" },
  { id: 7, title: "일곱 번째 책갈피", content: "이 책은 정말 흥미로워요!", author: "저자7", imageUrl: "https://example.com/book7.jpg" },
  { id: 8, title: "여덟 번째 책갈피", content: "이 책은 다른 책들과 비교했을 때 평범해요.", author: "저자8", imageUrl: "https://example.com/book8.jpg" },
  { id: 9, title: "아홉 번째 책갈피", content: "이 책은 생각보다 유익합니다.", author: "저자9", imageUrl: "https://example.com/book9.jpg" },
  { id: 10, title: "열 번째 책갈피", content: "이 책은 정말 짜증나요.", author: "저자10", imageUrl: "https://example.com/book10.jpg" },
  { id: 11, title: "열한 번째 책갈피", content: "이 책은 특별한 의미가 있어요.", author: "저자11", imageUrl: "https://example.com/book11.jpg" },
  { id: 12, title: "열두 번째 책갈피", content: "이 책은 완전 망했어요.", author: "저자12", imageUrl: "https://example.com/book12.jpg" },
  { id: 13, title: "열세 번째 책갈피", content: "이 책은 추천할만합니다.", author: "저자13", imageUrl: "https://example.com/book13.jpg" },
  { id: 14, title: "열네 번째 책갈피", content: "이 책은 너무 길어서 지루해요.", author: "저자14", imageUrl: "https://example.com/book14.jpg" },
  { id: 15, title: "열다섯 번째 책갈피", content: "이 책은 매우 인상 깊었습니다.", author: "저자15", imageUrl: "https://example.com/book15.jpg" },
  { id: 16, title: "열여섯 번째 책갈피", content: "이 책은 감동적인 이야기입니다.", author: "저자16", imageUrl: "https://example.com/book16.jpg" },
  { id: 17, title: "열일곱 번째 책갈피", content: "이 책은 문학적 가치가 큽니다.", author: "저자17", imageUrl: "https://example.com/book17.jpg" },
  { id: 18, title: "열여덟 번째 책갈피", content: "이 책은 과학적입니다.", author: "저자18", imageUrl: "https://example.com/book18.jpg" },
  { id: 19, title: "열아홉 번째 책갈피", content: "이 책은 좀 복잡하지만 유익합니다.", author: "저자19", imageUrl: "https://example.com/book19.jpg" },
  { id: 20, title: "스무 번째 책갈피", content: "이 책은 너무 현실적이어서 불편해요.", author: "저자20", imageUrl: "https://example.com/book20.jpg" },
  { id: 21, title: "스물한 번째 책갈피", content: "이 책은 따뜻하고 인간적입니다.", author: "저자21", imageUrl: "https://example.com/book21.jpg" },
  { id: 22, title: "스물두 번째 책갈피", content: "이 책은 감성적이에요.", author: "저자22", imageUrl: "https://example.com/book22.jpg" },
  { id: 23, title: "스물세 번째 책갈피", content: "이 책은 가볍게 읽기 좋습니다.", author: "저자23", imageUrl: "https://example.com/book23.jpg" },
  { id: 24, title: "스물네 번째 책갈피", content: "이 책은 매우 유머러스합니다.", author: "저자24", imageUrl: "https://example.com/book24.jpg" },
  { id: 25, title: "스물다섯 번째 책갈피", content: "이 책은 사실적인 이야기입니다.", author: "저자25", imageUrl: "https://example.com/book25.jpg" },
  { id: 26, title: "스물여섯 번째 책갈피", content: "이 책은 깊이가 있습니다.", author: "저자26", imageUrl: "https://example.com/book26.jpg" },
  { id: 27, title: "스물일곱 번째 책갈피", content: "이 책은 철학적인 내용이 많습니다.", author: "저자27", imageUrl: "https://example.com/book27.jpg" },
  { id: 28, title: "스물여덟 번째 책갈피", content: "이 책은 짧고 간결합니다.", author: "저자28", imageUrl: "https://example.com/book28.jpg" },
  { id: 29, title: "스물아홉 번째 책갈피", content: "이 책은 마음에 드네요.", author: "저자29", imageUrl: "https://example.com/book29.jpg" },
  { id: 30, title: "서른 번째 책갈피", content: "이 책은 미래에 대한 이야기입니다.", author: "저자30", imageUrl: "https://example.com/book30.jpg" },
];

export default dummyPosts;
